#pragma once

enum TEXTYPE { TEX_SINGLE, TEX_MULTI, TEX_END };
enum OBJID { OBJ_TERRAIN, OBJ_OBSTACLE, OBJ_WEAPON, OBJ_ENEMYBULLET, /*OBJ_ENEMY,*/ OBJ_PLAYERBULLET, OBJ_PLAYER, OBJ_MOUSE, OBJ_END };
enum WEAPONID { NO_WEAPON,RIFLE, SMG, SHOTGUN, CLUB, BAT, KNIFE, WEAPON_END };

enum MAPID { FLOOR, WALL, DOOR, DECO, WEAPON, MAP_END };
//enum LAYER { BACKGROUND, DECOOBJECT, GAMEOBJECT, EFFECT, UI, END };

enum DATAID { PLAYER_DATA, PLAYER_MATRIX, DATA_END };